image: node:14
before_script:
  - npm install

stages:
  # - build
  - test
  # - .post

# build-code-job:
#   stage: build
#   script:
#     - echo "Running Build..."
#     - npm run build

unit_test:
  stage: test
  image: node:14
  script:
    - echo "Running Tests..."
    - npx mocha app/app.test.js

# deploy-prod:
#   stage: .post
#   environment: production
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  